services:
  tas-landing:
    image: ghcr.io/travel-agency-service/tas-landing-nextjs:v0.1.0-2024-08-20-18-00-13
    build: .
    ports:
      - "3001:3000"

    restart: unless-stopped
    networks:
      - nginx-public

networks:
  nginx-public:
    external: true

