services:
  tas-landing:
    image: ghcr.io/travel-agency-service/tas-landing-nextjs:v0.2.0-2024-08-19-23-21-40
    build: .
    ports:
      - "3001:3000"

    restart: unless-stopped
    networks:
      - nginx-public

networks:
  nginx-public:
    external: true
